services:
  - name: flask-app
    envVars:
      - key: FLASK_APP
        value: "app.py"
    startCommand: "flask run --host=0.0.0.0 --port=$PORT"
    healthCheckPath: "/api/health"
    env:
      - key: RENDER_ENV
        value: "render"
